name: Run tests on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8
      - name: Run mypy
        run: mypy game_objects
      - name: Run pytests
        run: pytest -h tests
